[package]
name = "DPM-Core"
version = "0.1.2"
edition.workspace = true
authors.workspace = true
description = "DPM-Core is for DPM-Server & DPM-Client."
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/Derrick-Program/DPM-Core"
documentation = "https://docs.rs/dpm_core"
keywords = ["dpm", "repo", "Core", "self", "system"]
categories = ["command-line-utilities"]

[lib]
name = "dpm_core"
path = "src/lib.rs"

[features]
server = []
client = []

[dependencies]
anstyle.workspace = true
blake3 = "1.8.5"
clap.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
walkdir.workspace = true
zip.workspace = true

[dev-dependencies]
tokio.workspace = true
