[package]
name = "DPM-Core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "DPM-Core is for DPM-Server & DPM-Client."
license.workspace = true
readme = "README.md"
repository.workspace = true
documentation = "https://docs.rs/dpm_core"
keywords = ["dpm", "repo", "Core", "self", "system"]
categories = ["command-line-utilities"]

[lib]
name = "dpm_core"
path = "src/lib.rs"

[features]
server = []
client = []

[dependencies]
anstyle.workspace = true
blake3 = "1.8.5"
clap.workspace = true
config = { version = "0.15", default-features = false, features = ["toml"] }
ed25519-dalek = "2.1"
getrandom = "0.2"
hex = "0.4"
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
toml = "1"
walkdir.workspace = true
zip.workspace = true

[dev-dependencies]
tempfile = "3.10.1"
tokio.workspace = true
