[package]
name = "DPM"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "dpm"
path = "src/main.rs"

[dependencies]
DPM-Core = { workspace = true, features = ["client"] }
anyhow.workspace = true
clap.workspace = true
clap_complete.workspace = true
colored.workspace = true
directories = "6.0.0"
fs2 = "0.4.3"
futures-util.workspace = true
geni = "1.3.3"
git2 = { version = "0.18.1", features = ["vendored-openssl", "vendored-libgit2"] }
include_dir = "0.7.4"
libc = "0.2.153"
pubgrub = "0.4"
reqwest.workspace = true
self_update = { version = "0.44.0", features = ["archive-tar", "compression-flate2", "signatures"] }
semver = "1"
serde.workspace = true
serde_json.workspace = true
sudo = "0.6.0"
tempfile = "3.10.1"
thiserror.workspace = true
tokio.workspace = true
turso.workspace = true
