[package]
name = "DPM"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "dpm"
path = "src/main.rs"

[dependencies]
DPM-Core = { workspace = true, features = ["client"] }
anstyle.workspace = true
anyhow.workspace = true
clap.workspace = true
clap_complete.workspace = true
colored.workspace = true
directories = "6.0.0"
dotenv = "0.15.0"
flate2.workspace = true
fs2 = "0.4.3"
futures-util.workspace = true
geni = "1.3.3"
git2 = "0.18.1"
libc = "0.2.153"
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sudo = "0.6.0"
tempfile = "3.10.1"
thiserror.workspace = true
tokio.workspace = true
turso = "0.6.1"
walkdir.workspace = true
zip.workspace = true
