[package]
name = "DPM-Server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "DPM-Server is a server for the DPM-Client. It is a simple server that can be used to store and retrieve files from the DPM-Client."
repository = "https://github.com/Derrick-Program/DPM-Server"
readme = "README.md"
keywords = ["dpm", "repo", "Server", "self", "system"]
categories = ["command-line-utilities"]

[[bin]]
name = "dpm-server"
path = "src/main.rs"

[dependencies]
DPM-Core = { workspace = true, features = ["server"] }
anyhow.workspace = true
clap.workspace = true
colored.workspace = true
reqwest = { workspace = true, features = ["blocking"] }
thiserror.workspace = true
walkdir.workspace = true
